Fix for another unhandled exception.
This one would be caught by a previous fix to process_jobs().
This change restores the close() call to the connection.

ERROR: Could not Connect to Cloud Service. Will Try again in %d Seconds
012Traceback (most recent call last):
012  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 371, in process_jobs
012    XMPP_USE_SSL,xmpp_auth)
012  File "/usr/share/cloudprint/cloudprint/xmpp.py", line 123, in connect
012    self._msg('<auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="X-GOOGLE-TOKEN">%s</auth>' % sasl_token)
012  File "/usr/share/cloudprint/cloudprint/xmpp.py", line 87, in _msg
012    assert not elem.tag.endswith('failure') and not elem.tag.endswith('error')
012AssertionError
(cherry picked from commit 2c3582f87d281d612280def305871f8ce3dd20fc)